<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591;CA1515;CA1062;CA1303;IDE0011</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/EntityFrameworkCore.ManagedViews.PostgreSQL/EntityFrameworkCore.ManagedViews.PostgreSQL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Views/**/*.sql" />
  </ItemGroup>
</Project>
