<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>EntityFrameworkCore.ManagedViews.PostgreSQL</PackageId>
    <Description>PostgreSQL provider for EntityFrameworkCore.ManagedViews. Supports regular views, materialized views, and indexes on materialized views.</Description>
    <Authors>Nejdet</Authors>
    <PackageTags>efcore;entity-framework;views;postgresql;npgsql;materialized-view;managed-views</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/nejdetkadir/efcore-managed-views</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/nejdetkadir/efcore-managed-views</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../EntityFrameworkCore.ManagedViews/EntityFrameworkCore.ManagedViews.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
